- hosts: all
  #become: true
  user: ubuntu
  tasks:
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/service.yml

